---
- name: Install Nginx on Ubuntu 22.04
  hosts: aws_ec2
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: dd
      copy:
        content: kk
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0664'      
    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
