- name: Gather System Facts
  hosts: all
  gather_facts: true # 기본적으로 설정되어 있음
  tasks:
    - name: Display Hostname
      debug:
        msg: "The hostname is {{ ansible_hostname }}"
    - name: Display OS Family
      debug:
        msg: "The OS family is {{ ansible_os_family }}"
    - name: Display IP Address
      debug:
        msg: "The default IPv4 address is {{ ansible_default_ipv4.address }}"
    - name: Display CPU Information
      debug:
        msg: "CPU info: {{ ansible_processor }}"
    - name: Display Total Memory
      debug:
        msg: "Total Memory: {{ ansible_memtotal_mb }} MB"
